---

- name: Install Caddy/Php/Mysql
  hosts: 127.0.0.1
  connection: local
  roles:
    - role: geerlingguy.mysql
      become: yes
    - role: maxhoesel.caddy.caddy_server
      become: yes
      vars:
        caddy_config_mode: Caddyfile
        caddy_caddyfile: |
          {
              email admin@example.com
              on_demand_tls {
                  ask http://localhost:8400
              }
          }
          portal.floridarangers.com {
            log {
              output file         /var/log/access.log
              format single_field common_log
                  level debug
             }

             proxy / 127.0.0.1:8080 {
                transparent
             }

            metrics /metrics
          }
          http://localhost:8400 {
            respond "OK"
          }
