---


## Todo
## FixPerms www-data for php file and phpmyadmin in /usr/share/phpmyadmin
## Enable Services
- name: Install Caddy/Php/Mysql
  hosts: 127.0.0.1
  connection: local
  vars: 
    phpmyadmin_mysql_host: localhost
    phpmyadmin_mysql_port: ""
    phpmyadmin_mysql_socket: ""
    phpmyadmin_mysql_connect_type: tcp
    phpmyadmin_mysql_user: root
    phpmyadmin_mysql_password: "{{ mysql_root_password }}"
  tasks:
     - name: Ensure phpMyAdmin is installed.
       apt:
          name: phpmyadmin
          state: present
  roles:
    - role: markahesketh.ufw
      vars:
        ufw_rules:
          - to_port: 22
            rule: limit
          - to_port: 80
            rule: allow
          - to_port: 443
            rule: allow
    - role: geerlingguy.php-versions
      vars:
        php_version: '7.4'
    - role: geerlingguy.php
      vars:
        php_packages:
          - php7.4-gd
          - php7.4-cli
          - php7.4-common
          - php7.4-curl
          - php7.4-fpm
          - php7.4-intl
          - php7.4-json
          - php7.4-mbstring
          - php7.4-mysql
          - php7.4-opcache
          - php7.4-tidy
          - php7.4-xml
          - php7.4-zip
        php_webserver_daemon: "caddy"
        php_default_version_debian: "7.4"
        php_enable_php_fpm: true
        php_fpm_state: started
        php_fpm_enabled_on_boot: true
        php_use_managed_ini: true
    - role: geerlingguy.mysql
      become: yes
    - role: maxhoesel.caddy.caddy_server
      become: yes
      vars:
        caddy_config_mode: Caddyfile
        caddy_caddyfile: |
          {
    email admin@site.com
    on_demand_tls {
        ask http://localhost:8400
    }
}
site.com {

    root * /var/www/site.com

   log {
    output file         /var/log/access.log
    format single_field common_log
        level debug
   }

  php_fastcgi localhost:9000

  metrics /metrics
}

site.net {

   root * /var/www/site.net


   log {
    output file         /var/log/access.log
    format single_field common_log
        level debug
   }

   handle /myadmin/* {
        root * /usr/share/phpmyadmin
        uri strip_prefix /myadmin
        file_server browse
        php_fastcgi localhost:9000
   }

   file_server

   php_fastcgi localhost:9000

   metrics /metrics

}

http://localhost:8400 {
  respond "OK"
}
